// Code generated by goyacc -o filter/filter_parser.go filter/filter_parser.y. DO NOT EDIT.

//line filter/filter_parser.y:2
package filter

import __yyfmt__ "fmt"

//line filter/filter_parser.y:2

import (
	"strings"
	"time"
)

//line filter/filter_parser.y:9
type yySymType struct {
	yys   int
	token Token
	expr  Expression
}

const STRING = 57346
const NUMBER = 57347
const MONTH_IDENT = 57348
const TWELVE_CLOCK_IDENT = 57349
const TODAY_IDENT = 57350
const TOMORROW_IDENT = 57351
const YESTERDAY_IDENT = 57352
const DAYS = 57353
const VIEW = 57354
const ALL = 57355
const DUE = 57356
const BEFORE = 57357
const AFTER = 57358
const OVER = 57359
const OVERDUE = 57360
const NO = 57361
const DATE = 57362
const TIME = 57363
const LABELS = 57364

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"STRING",
	"NUMBER",
	"MONTH_IDENT",
	"TWELVE_CLOCK_IDENT",
	"TODAY_IDENT",
	"TOMORROW_IDENT",
	"YESTERDAY_IDENT",
	"DAYS",
	"VIEW",
	"ALL",
	"DUE",
	"BEFORE",
	"AFTER",
	"OVER",
	"OVERDUE",
	"NO",
	"DATE",
	"TIME",
	"LABELS",
	"'#'",
	"'@'",
	"'&'",
	"'|'",
	"'('",
	"')'",
	"'!'",
	"':'",
	"'/'",
}

var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line filter/filter_parser.y:245

//line yacctab:1
var yyExca = [...]int8{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 80

var yyAct = [...]int8{
	16, 3, 12, 23, 62, 25, 26, 27, 63, 13,
	39, 15, 37, 39, 19, 20, 14, 35, 37, 39,
	17, 18, 2, 60, 8, 59, 9, 29, 28, 48,
	54, 33, 34, 38, 29, 28, 38, 36, 44, 47,
	22, 58, 38, 36, 43, 41, 42, 45, 46, 40,
	68, 52, 53, 65, 23, 67, 25, 26, 27, 61,
	64, 66, 49, 57, 56, 55, 51, 50, 32, 31,
	30, 7, 6, 5, 4, 11, 10, 21, 24, 1,
}

var yyPact = [...]int16{
	-3, -1000, 9, -1000, 66, 65, 64, -1000, -3, -3,
	-1000, -1000, 6, 36, 24, 32, -1000, 16, -1000, 15,
	-1000, 62, -1000, 61, -1000, -1000, -1000, -1000, -3, -3,
	-1000, -1000, -1000, 2, 9, -1000, 60, 59, 58, -1000,
	-1000, -1000, -1000, -1000, 21, -5, -7, -1000, -1000, -1000,
	3, 54, -1000, -1000, -1000, -27, -1000, -22, -1000, 48,
	48, -1000, 50, 45, -1000, 12, -1000, -1000, -1000,
}

var yyPgo = [...]int8{
	0, 79, 22, 0, 78, 77, 76, 75, 74, 73,
	72, 71, 40,
}

var yyR1 = [...]int8{
	0, 1, 1, 2, 2, 2, 2, 2, 2, 2,
	2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
	9, 8, 10, 11, 7, 7, 6, 6, 3, 3,
	3, 5, 5, 5, 5, 5, 5, 5, 4, 4,
	4, 12, 12, 12,
}

var yyR2 = [...]int8{
	0, 0, 1, 3, 3, 1, 2, 2, 2, 1,
	3, 2, 1, 1, 2, 2, 2, 4, 4, 1,
	2, 1, 1, 2, 2, 3, 2, 1, 2, 1,
	1, 5, 3, 3, 1, 1, 1, 1, 2, 2,
	3, 3, 5, 2,
}

var yyChk = [...]int16{
	-1000, -1, -2, 4, -8, -9, -10, -11, 27, 29,
	-6, -7, 5, 12, 19, 14, -3, 23, 24, 17,
	18, -5, -12, 6, -4, 8, 9, 10, 26, 25,
	4, 4, 4, -2, -2, 11, 31, 6, 30, 7,
	13, 21, 22, 20, 14, 15, 16, 23, 14, -12,
	5, 5, -2, -2, 28, 5, 5, 5, 20, 30,
	30, 5, 31, 30, -3, 5, -3, 5, 5,
}

var yyDef = [...]int8{
	1, -2, 2, 5, 0, 0, 0, 9, 0, 0,
	12, 13, 0, 0, 0, 0, 19, 21, 22, 0,
	27, 29, 30, 0, 34, 35, 36, 37, 0, 0,
	6, 7, 8, 0, 11, 14, 0, 39, 0, 43,
	15, 16, 23, 24, 0, 0, 0, 20, 26, 28,
	0, 38, 3, 4, 10, 40, 33, 41, 25, 0,
	0, 32, 0, 0, 17, 0, 18, 31, 42,
}

var yyTok1 = [...]int8{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 29, 3, 23, 3, 3, 25, 3,
	27, 28, 3, 3, 3, 3, 3, 31, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 30, 3,
	3, 3, 3, 3, 24, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 26,
}

var yyTok2 = [...]int8{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22,
}

var yyTok3 = [...]int8{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := int(yyPact[state])
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && int(yyChk[int(yyAct[n])]) == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || int(yyExca[i+1]) != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := int(yyExca[i])
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = int(yyTok1[0])
		goto out
	}
	if char < len(yyTok1) {
		token = int(yyTok1[char])
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = int(yyTok2[char-yyPrivate])
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = int(yyTok3[i+0])
		if token == char {
			token = int(yyTok3[i+1])
			goto out
		}
	}

out:
	if token == 0 {
		token = int(yyTok2[1]) /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = int(yyPact[yystate])
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = int(yyAct[yyn])
	if int(yyChk[yyn]) == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = int(yyDef[yystate])
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && int(yyExca[xi+1]) == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = int(yyExca[xi+0])
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = int(yyExca[xi+1])
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = int(yyPact[yyS[yyp].yys]) + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = int(yyAct[yyn]) /* simulate a shift of "error" */
					if int(yyChk[yystate]) == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= int(yyR2[yyn])
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = int(yyR1[yyn])
	yyg := int(yyPgo[yyn])
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = int(yyAct[yyg])
	} else {
		yystate = int(yyAct[yyj])
		if int(yyChk[yystate]) != -yyn {
			yystate = int(yyAct[yyg])
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:
		yyDollar = yyS[yypt-0 : yypt+1]
//line filter/filter_parser.y:31
		{
			yyVAL.expr = VoidExpr{}
		}
	case 2:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:35
		{
			yyVAL.expr = yyDollar[1].expr
			yylex.(*Lexer).result = yyVAL.expr
		}
	case 3:
		yyDollar = yyS[yypt-3 : yypt+1]
//line filter/filter_parser.y:42
		{
			yyVAL.expr = BoolInfixOpExpr{left: yyDollar[1].expr, operator: '|', right: yyDollar[3].expr}
		}
	case 4:
		yyDollar = yyS[yypt-3 : yypt+1]
//line filter/filter_parser.y:46
		{
			yyVAL.expr = BoolInfixOpExpr{left: yyDollar[1].expr, operator: '&', right: yyDollar[3].expr}
		}
	case 5:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:50
		{
			yyVAL.expr = StringExpr{literal: yyDollar[1].token.literal}
		}
	case 6:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:54
		{
			yyVAL.expr = ProjectExpr{isAll: false, name: yyDollar[2].token.literal}
		}
	case 7:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:58
		{
			yyVAL.expr = ProjectExpr{isAll: true, name: yyDollar[2].token.literal}
		}
	case 8:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:62
		{
			yyVAL.expr = LabelExpr{name: yyDollar[2].token.literal}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:66
		{
			yyVAL.expr = LabelExpr{name: ""}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line filter/filter_parser.y:70
		{
			yyVAL.expr = yyDollar[2].expr
		}
	case 11:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:74
		{
			yyVAL.expr = NotOpExpr{expr: yyDollar[2].expr}
		}
	case 12:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:78
		{
			yyVAL.expr = DateExpr{allDay: false, datetime: now(), operation: DUE_BEFORE}
		}
	case 13:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:82
		{
			yyVAL.expr = DateExpr{operation: NO_DUE_DATE}
		}
	case 14:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:86
		{
			date := today().AddDate(0, 0, atoi(yyDollar[1].token.literal))
			yyVAL.expr = DateExpr{allDay: true, datetime: date, operation: DUE_BEFORE}
		}
	case 15:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:91
		{
			yyVAL.expr = ViewAllExpr{}
		}
	case 16:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:95
		{
			yyVAL.expr = DateExpr{operation: NO_TIME}
		}
	case 17:
		yyDollar = yyS[yypt-4 : yypt+1]
//line filter/filter_parser.y:99
		{
			e := yyDollar[4].expr.(DateExpr)
			e.operation = DUE_BEFORE
			yyVAL.expr = e
		}
	case 18:
		yyDollar = yyS[yypt-4 : yypt+1]
//line filter/filter_parser.y:105
		{
			e := yyDollar[4].expr.(DateExpr)
			e.operation = DUE_AFTER
			yyVAL.expr = e
		}
	case 20:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:114
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 21:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:120
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 22:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:126
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 23:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:132
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 24:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:138
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 25:
		yyDollar = yyS[yypt-3 : yypt+1]
//line filter/filter_parser.y:142
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 26:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:148
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 27:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:152
		{
			yyVAL.expr = yyDollar[1].token
		}
	case 28:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:159
		{
			date := yyDollar[1].expr.(time.Time)
			time := yyDollar[2].expr.(time.Duration)
			yyVAL.expr = DateExpr{allDay: false, datetime: date.Add(time)}
		}
	case 29:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:165
		{
			yyVAL.expr = DateExpr{allDay: true, datetime: yyDollar[1].expr.(time.Time)}
		}
	case 30:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:169
		{
			nd := now().Sub(today())
			d := yyDollar[1].expr.(time.Duration)
			if d <= nd {
				d = d + time.Duration(int64(time.Hour)*24)
			}
			yyVAL.expr = DateExpr{allDay: false, datetime: today().Add(d)}
		}
	case 31:
		yyDollar = yyS[yypt-5 : yypt+1]
//line filter/filter_parser.y:180
		{
			yyVAL.expr = time.Date(atoi(yyDollar[5].token.literal), time.Month(atoi(yyDollar[1].token.literal)), atoi(yyDollar[3].token.literal), 0, 0, 0, 0, timezone())
		}
	case 32:
		yyDollar = yyS[yypt-3 : yypt+1]
//line filter/filter_parser.y:184
		{
			yyVAL.expr = time.Date(atoi(yyDollar[3].token.literal), MonthIdentHash[strings.ToLower(yyDollar[1].token.literal)], atoi(yyDollar[2].token.literal), 0, 0, 0, 0, timezone())
		}
	case 33:
		yyDollar = yyS[yypt-3 : yypt+1]
//line filter/filter_parser.y:188
		{
			yyVAL.expr = time.Date(atoi(yyDollar[3].token.literal), MonthIdentHash[strings.ToLower(yyDollar[2].token.literal)], atoi(yyDollar[1].token.literal), 0, 0, 0, 0, timezone())
		}
	case 34:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:192
		{
			tod := today()
			date := yyDollar[1].expr.(time.Time)
			if date.Before(tod) {
				date = date.AddDate(1, 0, 0)
			}
			yyVAL.expr = date
		}
	case 35:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:201
		{
			yyVAL.expr = today()
		}
	case 36:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:205
		{
			yyVAL.expr = today().AddDate(0, 0, 1)
		}
	case 37:
		yyDollar = yyS[yypt-1 : yypt+1]
//line filter/filter_parser.y:209
		{
			yyVAL.expr = today().AddDate(0, 0, -1)
		}
	case 38:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:215
		{
			yyVAL.expr = time.Date(today().Year(), MonthIdentHash[strings.ToLower(yyDollar[1].token.literal)], atoi(yyDollar[2].token.literal), 0, 0, 0, 0, timezone())
		}
	case 39:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:219
		{
			yyVAL.expr = time.Date(today().Year(), MonthIdentHash[strings.ToLower(yyDollar[2].token.literal)], atoi(yyDollar[1].token.literal), 0, 0, 0, 0, timezone())
		}
	case 40:
		yyDollar = yyS[yypt-3 : yypt+1]
//line filter/filter_parser.y:223
		{
			yyVAL.expr = time.Date(now().Year(), time.Month(atoi(yyDollar[3].token.literal)), atoi(yyDollar[1].token.literal), 0, 0, 0, 0, timezone())
		}
	case 41:
		yyDollar = yyS[yypt-3 : yypt+1]
//line filter/filter_parser.y:229
		{
			yyVAL.expr = time.Duration(int64(time.Hour)*int64(atoi(yyDollar[1].token.literal)) + int64(time.Minute)*int64(atoi(yyDollar[3].token.literal)))
		}
	case 42:
		yyDollar = yyS[yypt-5 : yypt+1]
//line filter/filter_parser.y:233
		{
			yyVAL.expr = time.Duration(int64(time.Hour)*int64(atoi(yyDollar[1].token.literal)) + int64(time.Minute)*int64(atoi(yyDollar[3].token.literal)) + int64(time.Second)*int64(atoi(yyDollar[5].token.literal)))
		}
	case 43:
		yyDollar = yyS[yypt-2 : yypt+1]
//line filter/filter_parser.y:237
		{
			hour := atoi(yyDollar[1].token.literal)
			if TwelveClockIdentHash[yyDollar[2].token.literal] {
				hour = hour + 12
			}
			yyVAL.expr = time.Duration(int64(time.Hour) * int64(hour))
		}
	}
	goto yystack /* stack new state and value */
}
