name: Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Generate build files
        uses: psethwick/go-cross-build@1.2.0
        with:
          platforms: 'linux/amd64, darwin/amd64, windows/amd64'
          package: ''
          name: 'tuidoist'
          compress: 'true'
          dest: 'dist'
      - name: Publish Binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: Release ${{ github.ref_name }}
          tag: ${{ github.ref }}
          file: dist/*
          file_glob: true
          overwrite: true
